services:
  scraper:
    build: .
    environment:
      - CARD_RETRIEVAL_DATABASE_URL=${CARD_RETRIEVAL_DATABASE_URL}
      - CARD_RETRIEVAL_BROWSER_HEADLESS=false
    entrypoint: ["/app/entrypoint.sh"]
    command: []
    restart: unless-stopped
