"""initial schema with unique constraint

Revision ID: c8934ac349bf
Revises: 
Create Date: 2026-03-18 14:08:46.257282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8934ac349bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('card_types', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True),
    sa.Column('discount_value', sa.String(length=100), nullable=True),
    sa.Column('minimum_spend', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank', 'source_id', name='uq_bank_source_id'),
    sqlite_autoincrement=False
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('ix_bank_source_id', ['bank', 'source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_is_active'), ['is_active'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promotions_found', sa.Integer(), nullable=False),
    sa.Column('promotions_new', sa.Integer(), nullable=False),
    sa.Column('promotions_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_bank'), ['bank'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_bank'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_is_active'))
        batch_op.drop_index(batch_op.f('ix_promotions_bank'))
        batch_op.drop_index('ix_bank_source_id')

    op.drop_table('promotions')
    # ### end Alembic commands ###
